spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/spring-framework?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: root

## mybatis-plus
mybatis-plus:
  # *mapper.xml 位置
  mapper-locations: classpath:/mapperxmls/**/*.xml
  # entity包位置
  type-aliases-package: com.isfong.spring.boot.apply.model
  # 枚举包位置
  #typeEnumsPackage:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null