server:
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master, slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:13306/spring-framework?characterEncoding=utf-8
        username: root
        password: root
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:23306/spring-framework?characterEncoding=utf-8
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true

## mybatis-plus
mybatis-plus:
  # *mapper.xml 位置
  mapper-locations: classpath:/mapperxmls/**/*.xml
  # entity包位置
  type-aliases-package: com.isfong.spring.boot.apply.model
  # 枚举包位置
  #typeEnumsPackage:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
#logging:
#  level:
#    com.isfong.spring.boot.apply.mapper: debug